name: checkout@v3 
on: push 
jobs:
  checkout_ls:
    run-on: ubuntu-latest
    steps:
      - name: LS output before checkout
        run: ls
      - name: Checkout code
        run: git clone https://github.com/mehmettozdemir/second-action-react-demo.git
      - name: LS output after checkout
        run: ls