name: checkout@v3 
on: push 
jobs:
  checkout_ls:
    runs-on: ubuntu-latest
    steps:
      - name: LS output before checkout
        run: ls
      - name: Checkout code
        uses: actions/checkout@v3
      - name: LS output after checkout
        run: ls